apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-bot-webapp
  namespace: sailingapp
  labels:
    app: yas-bot-webapp
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: yas-bot-webapp
  template:
    metadata:
      labels:
        app: yas-bot-webapp
        version: v1
    spec:
      containers:
      - name: yas-bot-webapp
        image: ilaverlin/yas-bot-webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

