apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Setting the base resources
resources:
  - ../../base

# Patches
patches:

  - target:
      group: "traefik.io"
      version: "v1alpha1"
      kind: "IngressRoute"
      name: "yas-bot-webapp"
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/routes/0/match",
          "value": "Host(`ivan-b.com`) && PathPrefix(`/yas-bot/`)"
        }
      ]

# Optional: override common annotations for the dev environment
commonAnnotations:
  environment: "dev"
  version: "latest"