apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailingapp-botwebapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Laverlin/yas-bot-webapp.git'
    path: "deploy/webapp/overlays/<overlay-name>"
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sailingapp
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground