# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: generate semver
      uses: paulhatch/semantic-version@v5.1.0
      id: semver
      with:
        tag_prefix: "v"
        major_pattern: "[MAJOR]"
        minor_pattern: "[MINOR]"
        search_commit_body: true
        version_format: ${major}.${minor}.${patch}${{ (!contains(github.event.head_commit.message, '[MINOR]') && !contains(github.event.head_commit.message, '[MAJOR]')) && '-beta+${increment}' || '' }}


    - name: patch package.json
      run: |
        mv ${{ github.workspace }}/package.json ${{ github.workspace }}/package.original.json
        jq '.version = "${{ steps.semver.outputs.version }}"' ${{ github.workspace }}/package.original.json > ${{ github.workspace }}/package.json

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: zip results
      run: |
        pushd ${{ github.workspace }}/build
        zip -r ${{ github.workspace }}/build-${{ steps.semver.outputs.version_tag }}.zip *
        popd

    - name: Create a Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      with:
        tag_name: ${{ steps.semver.outputs.version_tag }}

  # A release created by shogo82148/actions-create-release is alway draft here.
  # So users may not see an empty release.

    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build-${{ steps.semver.outputs.version_tag }}.zip
        asset_name: build-${{ steps.semver.outputs.version_tag }}.zip

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: generate semver
      uses: paulhatch/semantic-version@v5.1.0
      id: semver
      with:
        tag_prefix: "v"
        major_pattern: "[MAJOR]"
        minor_pattern: "[MINOR]"
        search_commit_body: true
        version_format: ${major}.${minor}.${patch}${{ (!contains(github.event.head_commit.message, '[MINOR]') && !contains(github.event.head_commit.message, '[MAJOR]')) && '-beta+${increment}' || '' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/yas-bot-webapp
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.semver.outputs.version }}
          type=semver,pattern={{major}},value=${{ steps.semver.outputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

